import Head from "next/head";
// import Todos from "../../components/Todos";
import { useEffect, useState } from "react";
import axios from "axios";
import io from "socket.io-client";
import CustomEvent from '../../utils/events';

let socket;

const Dashboard = () => {
  const [message, setMessage] = useState("");
  const [allSMS, setAllSMS] = useState([]);


  // making the the socket connection when the page is loaded...

  const makeSocketConnection = async () => {
    try {
     
      socket = io("http://localhost:5000/");
      

      socket.on("connect", () => {
        console.log("connected to the server!");
      });
    } catch (error) {
      console.log(error);
    }
  };


  const handleChange = (e) => {
    setMessage(e.target.value);
  };
  const handleSubmit = () => {
   
    socket.emit("test__SocketServer", message);
    socket.on("test__messageSendBack", (data) => {
      setAllSMS([...allSMS, data.message]);
      console.log(data.message, "from the server");
    });
    
  };
  useEffect(() => {
    makeSocketConnection();    

  }, []);
  return (
    <>
      <Head>
        <title>E-comm. - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-[50vh] w-full  flex flex-col justify-center items-center">
        {allSMS.map((cur, id) => (
          <li className="" key={id}>
            {cur}
          </li>
        ))}
        <div className="h-auto flex justify-evenly items-center w-[90vh]">
          <input
            onChange={handleChange}
            name="message"
            placeholder="the message"
            className="p-1 font-semibold bg-red-50"
          />
          <button
            onClick={handleSubmit}
            className="bg-red-400 text-white px-3 py-1 font-semibold"
          >
            Submit
          </button>
        </div>
      </div>
      <div></div>
    </>
  );
};

export default Dashboard;
